### ISSUE TITLE
How do you manage this repo, by another way, how can I contribute something to this repo?

### ISSUE THREAD

**Issue by pierce-shelby** [liusy58/WhyThis#29]

**Comment by liusy58** [comment]
Sorry for my late response. You can contribute by making a pull request~ If you want to join us and help us maintain this repo, I can add you to the collaborator list. And the most simple way is to new a discussion
![image](https://user-images.githubusercontent.com/45984215/117598320-26cc9400-b17a-11eb-9ad9-f49d2c3d5560.png)
