### ISSUE TITLE
关于“为什么main"不是"程序的入口？”

### ISSUE THREAD

**Issue by JYuniform64** [liusy58/WhyThis#44]
>那么因为没有函数调用过main函数，那么肯定会发生错误，所以在程序装载的时候，操作系统肯定是加入了其他的代码来跳转到 main函数的执行的。

事实上入口函数往往是运行库的一部分，这个过程发生在链接阶段，而非通过OS添加代码的方式实现。

另建议进一步通过 demo 及其目标文件演示入口函数所作的工作，以说明 “main不是程序的入口” 的必要性。

**Comment by JYuniform64** [comment]
另建议将这个问题归入 compiler 中。

**Comment by liusy58** [comment]
Sorry for my late response. In reality,  loader is just the operating system (OS) 

这个之所以放在OS里面是因为涉及到了虚拟内存等内容，毕竟四大块本来就是不可区分的。至于例子，我会考虑添加的，多谢你的建议。

**Comment by liusy58** [comment]
Sorry for my late response. I'll consider your suggestion later~
